apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nug-console-link
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: console-customisations/
    repoURL: 'https://github.com/asshutossh/openshift-cluster-bootstrap.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
